# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IOT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from numpy import random

from PyQt5 import QtCore, QtGui, QtWidgets
import imagehe

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 170, 100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 250, 100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 320, 100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 400, 100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 470, 100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 650, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 200, 170))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("image: url(:/myimage/off.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 250, 200, 150))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("image: url(:/myimage/pc1.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 400, 200, 150))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("image: url(:/myimage/switch1.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 170,100 , 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(330, 320, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(330, 470, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 600, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 100, 90))
        self.label_6.setStyleSheet("image: url(:/myimage/ute.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 100, 450, 450))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel) 
        self.frame.setObjectName("frame")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.figure =plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.horizontalLayout_4.addWidget(self.canvas)

        
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.plotOnCanvas())
        self.pushButton_10.setGeometry(QtCore.QRect(600, 560, 150, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10") 
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 447, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.pushButton_9.clicked.connect(self.pushButton_9.close) # type: ignore
        self.pushButton_9.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.pushButton.clicked.connect(self.on) # khi nút on lên mức 1 thì hàm on sẽ được gọi
        self.pushButton_2.clicked.connect(self.off) # tương tự nút on

        self.pushButton_3.clicked.connect(self.on1) # khi nút on lên mức 1 thì hàm on sẽ được gọi
        self.pushButton_4.clicked.connect(self.off1) # tương tự nút on

        self.pushButton_5.clicked.connect(self.on2) # khi nút on lên mức 1 thì hàm on sẽ được gọi
        self.pushButton_6.clicked.connect(self.off2) # tương tự nút on

        self.pushButton_7.clicked.connect(self.on3) # tương tự nút on
        self.pushButton_9.clicked.connect(self.off3) # tương tự nút on
        self.pushButton_8.clicked.connect(self.on4) # tương tự nút on

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ON 1"))
        self.pushButton_2.setText(_translate("MainWindow", "OFF 1"))
        self.pushButton_3.setText(_translate("MainWindow", "ON 2"))
        self.pushButton_4.setText(_translate("MainWindow", "OFF 2"))
        self.pushButton_5.setText(_translate("MainWindow", "ON 3"))
        self.pushButton_6.setText(_translate("MainWindow", "OFF 3"))
        self.label.setText(_translate("MainWindow", "IOT DREAM ROOM "))
        self.pushButton_7.setText(_translate("MainWindow", "PLAY"))
        self.pushButton_8.setText(_translate("MainWindow", "STUDY"))
        self.pushButton_9.setText(_translate("MainWindow", "EXIT"))
        self.label_5.setText(_translate("MainWindow", "ĐỖ QUANG ĐĂNG KHOA-22119089"))
        self.pushButton_10.setText(_translate("MainWindow", "NHẤN"))

    def on(self):
            self.label_2.setStyleSheet("image: url(:/myimage/on.png);") #gọi ảnh đã lưu trong style sheet
    def off(self):
        self.label_2.setStyleSheet("image: url(:/myimage/off.png);")
    
    def on1(self):
        self.label_3.setStyleSheet("image: url(:/myimage/pc2.png);") #gọi ảnh đã lưu trong style sheet
    def off1(self):
        self.label_3.setStyleSheet("image: url(:/myimage/pc1.png);")
    
    def on2(self):
        self.label_4.setStyleSheet("image: url(:/myimage/switch2.png);") #gọi ảnh đã lưu trong style sheet
    def off2(self):
        self.label_4.setStyleSheet("image: url(:/myimage/switch1.png);")
    def on3(self):
        self.label_4.setStyleSheet("image: url(:/myimage/switch2.png);")
        self.label_3.setStyleSheet("image: url(:/myimage/pc2.png);")
        self.label_2.setStyleSheet("image: url(:/myimage/on.png);")
    def off3(self):
        self.label_2.setStyleSheet("image: url(:/myimage/off.png);")
        self.label_3.setStyleSheet("image: url(:/myimage/pc1.png);")
        self.label_4.setStyleSheet("image: url(:/myimage/switch1.png);")

    def on4(self):
        self.label_3.setStyleSheet("image: url(:/myimage/pc3.png);")
        self.label_2.setStyleSheet("image: url(:/myimage/on.png);")
        self.label_4.setStyleSheet("image: url(:/myimage/switch1.png);")
   

         
    
    def plotOnCanvas(self):
        self.figure.clear()

        Days = ['NGAY HOC','NGAY CHOI']
        values = random.randint(8,size=(2))
        print(values)

        plt.bar(Days, values, color = 'red', width = 0.5)
        plt.xlabel ('CÔNG VIỆC')
        plt.ylabel ('NGÀY')
        plt.title('THỜI KHÓA BIỂU CỦA KHOA')

        self.canvas.draw()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


